Flow definition
code0-tech/pictor pull request #236
Opened 2024-11-14 20:55 UTC by nicosammito

2024-12-27 19:04 UTC, Knerio requested changes

2024-12-27 19:04 UTC, Knerio commented on docs/flow-definition.ts
> +    name: string
Shouldnt this be a Translation[]?

2024-12-27 19:04 UTC, Knerio commented on docs/flow-definition.ts
> +    name: Translation
Shouldnt this be a Translation[]

2024-12-27 19:04 UTC, Knerio commented on docs/flow-definition.ts
> +    name: Translation // overrides the runtime parameter name and ref to language entry
Shouldnt this be a Translation[]

2024-12-27 19:04 UTC, Knerio commented on docs/flow-definition.ts
> +    description: Translation
Shouldnt this be a Translation[]

2024-12-28 15:44 UTC, raphael-goetz approved these changes

2025-01-03 00:35 UTC, nicosammito commented on docs/flow-definition.ts
> +interface FlowDefinitionSetting {
We need to add a `unique` property. For example the endpoint of a REST Flow must be unique across a project

2025-01-03 00:35 UTC, nicosammito commented on docs/flow-definition.ts
> +interface FlowDefinition {
Every FlowDefinition should contain an input_type property with a default_value.

2025-01-03 00:35 UTC, nicosammito commented on docs/flow-definition.ts
> +enum EDataTypeRuleType {
We need a RuleType field for locking specific keys on a OBJECT DataType. This prevents the user to change the value. It will then internally always fallback to the default_value

2025-01-03 14:44 UTC, nicosammito commented on docs/flow-definition.ts
> +}
```suggestion
interface FlowDefinitionSetting {
    name: Translation[]
    unique: boolean
    description: Translation[]
    type: DataType
    default_value?: object
}
```

2025-01-03 14:44 UTC, nicosammito commented on docs/flow-definition.ts
> +    //etc
```suggestion
    LOCK_KEY,
    //etc
```

2025-01-03 14:44 UTC, nicosammito commented on docs/flow-definition.ts
> +}
```suggestion
interface FlowDefinition {
    settings: FlowDefinitionSetting[]
    input_type: DataType
    default_input_value: object
}
```

2025-01-03 14:44 UTC, nicosammito commented on docs/flow-definition.ts
> +}
```suggestion
interface Flow {
    type: FlowType | string //in the actual implementation we will just link the name or id
    settings: FlowSetting[]
    starting_node: NodeFunction
    input_value?: object
}
```

2025-01-03 15:43 UTC, nicosammito commented on docs/flow-definition.ts
> +    default_input_value: object
```suggestion
    editable: boolean
```

2025-01-03 15:56 UTC, raphael-goetz approved these changes

2025-01-03 16:03 UTC, merged