Implement needed Select Component
code0-tech/pictor pull request #52
Opened 2024-02-14 10:45 UTC by Knerio

This PR would resolve https://github.com/code0-tech/pictor/issues/44

2024-02-14 21:39 UTC, nicosammito requested changes
Good work, but some small changes

2024-02-14 21:39 UTC, nicosammito commented on src/components/select/Select.tsx
> +    children: TablerIconsProps
Why we should allow to parse in an icon as a child component?
This does not make sense in my opinion. Also we always allow more than just icons from Tabler

2024-02-14 21:39 UTC, nicosammito commented on src/components/select/Select.tsx
> +}
`forbidDeselect` is not matching our naming convention. It should be more like disallowDeselection

Also we are missing a lot of props here like `label` and event listeners like `onSelectionChange`

2024-02-14 21:39 UTC, nicosammito commented on src/components/select/Select.tsx
> +    children: string
I rethought this and we should support more than just strings here. Imagine you would like to style the option in your way and add for example a email address as a Badge inside the option

2024-02-14 21:39 UTC, nicosammito commented on src/components/select/Select.tsx
> +}
We move those as props to the component itself and do not map it as child components. Icon we completely remove

2024-02-14 21:39 UTC, nicosammito commented on src/components/select/Select.tsx
> +}
Also we should add something like clearable. But thus should be implemented on the Input component.

So maybe we should first add some functionality to the Input components and come back to the MR than

2024-02-14 21:39 UTC, nicosammito commented on src/components/menu/Menu.tsx
> +                {menuTrigger ? React.cloneElement(menuTrigger.props.children, { ...(!state.isOpen && {tabIndex: 1})}) : null}
You should test if all the keyboard actions are still working as intended. Otherwise just remove the type from buttonProps

2024-02-14 21:42 UTC, nicosammito commented
![IMG_3074](https://github.com/code0-tech/pictor/assets/60352747/c68d79ba-de76-4536-91fa-800fc5d6db28)

Also the tabIndex is on the full Select rather than just on the Input

2024-02-15 09:46 UTC, Knerio commented on src/components/select/Select.tsx
> +}
The label prop is managed through a child component just like in the input:

```ts
            <Select description={"Lorem ipsum"} defaultValue={defaultValue}>
                <Select.Label>{label}</Select.Label>
                <Select.Option>Lorem ipsum 1</Select.Option>
                <Select.Option>Lorem ipsum 2</Select.Option>
            </Select>
```

2024-02-15 09:55 UTC, Knerio commented on src/components/menu/Menu.tsx
> +                {menuTrigger ? React.cloneElement(menuTrigger.props.children, { ...(!state.isOpen && {tabIndex: 1})}) : null}
I dont really get what you mean by that, you told me I should just remove it

2024-02-15 10:24 UTC, Knerio commented on src/components/select/Select.tsx
> +    children: TablerIconsProps
I have oriented myself to the input and there only the tabler icons are supported:

```ts
export type InputControlIconType = {
    children: ReactElement<TablerIconsProps>
}
```

2024-02-15 10:26 UTC, nicosammito commented on src/components/select/Select.tsx
> +    children: TablerIconsProps
There is currently a issue opens that completely redevelopes the input component. So please do not take this as a reference

2024-02-15 10:26 UTC, nicosammito commented on src/components/select/Select.tsx
> +}
Let's move this one to the props of the select component like in mantine

2024-02-15 11:49 UTC, Knerio commented on src/components/select/Select.tsx
> +    children: TablerIconsProps
But should I set an icon to the input then?

2024-02-15 16:05 UTC, nicosammito requested changes

2024-02-15 16:05 UTC, nicosammito commented on src/components/select/Select.tsx
> +}
we need to add some docs for each prop that shows the default value. Also disabled e.g. misses a default value

2024-02-15 16:05 UTC, nicosammito commented on src/components/select/Select.tsx
> +export interface Event {
Give it a better name like `SelectEvent`

2024-02-15 16:05 UTC, nicosammito commented on src/components/select/Select.tsx
> +//These components doesnt exists, waiting for Nico
Important node: we are not merging until this is developed

2024-02-15 16:05 UTC, nicosammito commented on src/components/select/Select.style.scss
> +.input__control {
why this is named input?

2024-02-15 16:05 UTC, nicosammito commented on src/components/select/Select.tsx
> +                    <InputComponent/>
you are using props but not parsing them through

2024-02-15 16:06 UTC, nicosammito commented
![Bildschirmfoto 2024-02-15 um 17 05 46](https://github.com/code0-tech/pictor/assets/60352747/3296dda1-3e20-45c6-bc24-e4b6d477f563)

It's selecting the parent component rather the input component. It needs to tabs to select the right one.

2024-02-15 16:09 UTC, nicosammito commented
![Bildschirmfoto 2024-02-15 um 17 09 01](https://github.com/code0-tech/pictor/assets/60352747/e8d53f65-b08a-47b0-b31c-789fbf7c3e4c)

Clearable should not replace the select icon.

2024-02-15 16:12 UTC, Taucher2003 commented on src/components/select/Select.stories.tsx
Instead of creating many different stories that only have different props, you should probably look at the storybook controls to change these props.

2024-02-15 16:14 UTC, nicosammito commented on src/components/select/Select.stories.tsx
No this is fine for the moment. Generally you are right but this way we can easily check the functionality also on mobile devices. Unfortunately storybook is not optimized for mobile usage.

2024-02-15 16:15 UTC, Knerio commented on src/components/select/Select.stories.tsx
> +export const Selection: MenuStory = {
You mean an element to set an option?

2024-02-15 16:16 UTC, nicosammito commented on src/components/select/Select.stories.tsx
> +export const Selection: MenuStory = {
yes something similar to the account list we have in menu

2024-02-15 16:22 UTC, Knerio commented on src/components/select/Select.stories.tsx
> +export const Selection: MenuStory = {
How would this be used, in the code and on the website i dont see any uses

2024-02-15 16:32 UTC, Knerio commented on src/components/select/Select.style.scss
> +.input__control {
Because this should get the class of the input not the select to change the cursor

2024-02-15 16:35 UTC, Knerio commented on src/components/select/Select.stories.tsx
And its also quicker than changing specific props

2024-02-15 16:37 UTC, Knerio commented
> ![Bildschirmfoto 2024-02-15 um 17 09 01](https://private-user-images.githubusercontent.com/60352747/305141092-e8d53f65-b08a-47b0-b31c-789fbf7c3e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQyMDAsIm5iZiI6MTcwODAxMzkwMCwicGF0aCI6Ii82MDM1Mjc0Ny8zMDUxNDEwOTItZThkNTNmNjUtYjA4YS00N2IwLWIzMWMtNzg5ZmJmN2MzZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOGM0MDNiZjQ4YjA3MzI1NTI2MjY2Mzc2NTk5ZjJlYzQzMmFiOGE1OTc3NjJiMjkzNTEwNGUzOWQxMjkyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9MIRudMhy7xpUyKMLGYKTbwQILiRrVpfx3e-JyJ91mY)
> 
> Clearable should not replace the select icon.

How would i wrap that in the input then? The input doesnt support that

2024-02-15 16:39 UTC, Knerio commented
> ![Bildschirmfoto 2024-02-15 um 17 05 46](https://private-user-images.githubusercontent.com/60352747/305140136-3296dda1-3e20-45c6-bc24-e4b6d477f563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQyMDAsIm5iZiI6MTcwODAxMzkwMCwicGF0aCI6Ii82MDM1Mjc0Ny8zMDUxNDAxMzYtMzI5NmRkYTEtM2UyMC00NWM2LWJjMjQtZTRiNmQ0NzdmNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWQ0NjhmOTkxMzc0OGU1NTYwM2ViMjM3MDAwNjc5NDEyZmM1ZDRkYjNlOGQwYzZiMDExYzI2MDZmNGUzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydU8zIqd8G5jO1udppcS1jPWOwc7AxA3--wqWRxSliE)
> 
> It's selecting the parent component rather the input component. It needs to tabs to select the right one.

On my machine the enter still works and i cant really decide which one to tab

2024-02-15 16:40 UTC, Knerio commented on src/components/select/Select.tsx
> +//These components doesnt exists, waiting for Nico
I have to wait for you to develop the label etc..

2024-02-15 17:37 UTC, nicosammito commented
> > ![Bildschirmfoto 2024-02-15 um 17 05 46](https://private-user-images.githubusercontent.com/60352747/305140136-3296dda1-3e20-45c6-bc24-e4b6d477f563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQyMDAsIm5iZiI6MTcwODAxMzkwMCwicGF0aCI6Ii82MDM1Mjc0Ny8zMDUxNDAxMzYtMzI5NmRkYTEtM2UyMC00NWM2LWJjMjQtZTRiNmQ0NzdmNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWQ0NjhmOTkxMzc0OGU1NTYwM2ViMjM3MDAwNjc5NDEyZmM1ZDRkYjNlOGQwYzZiMDExYzI2MDZmNGUzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydU8zIqd8G5jO1udppcS1jPWOwc7AxA3--wqWRxSliE)
> > It's selecting the parent component rather the input component. It needs to tabs to select the right one.
> 
> On my machine the enter still works and i cant really decide which one to tab

The tab should be directly on the input rather on the wrapper. I think it was my mistake inside the menu component. Would be great if you can check this one

2024-05-18 12:53 UTC, Taucher2003 requested changes

2024-05-18 18:30 UTC, nicosammito approved these changes

2024-05-18 18:31 UTC, merged