Issue 30/more button styles
code0-tech/pictor pull request #59
Opened 2024-02-16 21:22 UTC by raphael-goetz

Solved Issue #30
- added variants to buttons: none, normal, filled, outlined
- renamed prop "variants" to "color"

2024-02-16 21:40 UTC, Taucher2003 commented on src/components/button/Button.tsx
> +    variant?: "none" | "normal" | "outlined" | "filled",
You have renamed the `variant` prop to `color`. Please make sure to update all usages of the prop as well.

Looking at the failed snapshot tests (https://gitlab.com/code0-tech/pictor/-/jobs/6194085242/artifacts/browse/__snapshots__/__diff_output__/), it looks like at least the Button/ButtonGroups, Card/Test and Dropdown/Dropdowns stories are affected.

2024-02-16 21:40 UTC, Taucher2003 commented on src/components/button/Button.style.scss
> +    &.button__withoutBorder {
Naming convention for css would be `button--without-border` (Also applies to the other classes)

But I do think that we should name the classes like their actual variants. So something like `button--none`, `button--filled` and `button--outlined`.

2024-02-16 21:40 UTC, Taucher2003 commented on src/components/button/Button.tsx
> +    }
This is static and does not need to be a function. What do you think about making this a mapping object?
```suggestion
    const variantMappings = {
      none: "button--without-all",
      outlined: "button--without-border",
      filled: "button--without-background"
    }
```

Then you can get the variant like this: `variantMappings[variant] ?? ""`

2024-02-17 01:13 UTC, nicosammito requested changes
Great work, just a small change request 👍🏻

2024-02-17 01:13 UTC, nicosammito commented on src/components/button/Button.style.scss
> +        background: mix($bodyBg, if($color == $primary, $white, $color), if($color == $primary, 90%, 80%));
duplicated code here for background and border-color. We should outsource this into a function in helpers and reuse it everywhere we need it

2024-02-18 12:30 UTC, nicosammito approved these changes

2024-02-18 13:27 UTC, merged