Pill Component
code0-tech/pictor pull request #64
Opened 2024-02-17 20:06 UTC by Knerio

This PR would resolve https://github.com/code0-tech/pictor/issues/63

This component is also needed for https://github.com/code0-tech/pictor/issues/62

2024-02-18 12:38 UTC, nicosammito requested changes

2024-02-18 12:38 UTC, nicosammito commented on __snapshots__/pill--with-href-chromium.png
Padding mismatch on all Pills. More padding at the top as on the bottom

2024-02-18 12:38 UTC, nicosammito commented on src/components/pill/Pill.style.scss
> +);
We need to have a discussion about the font-sizes. As you see in helpers we already have defined 3 variants, but we definitely need more here. What do you think should we use for the sizes to match our pattern as we defined it in variables.scss

2024-02-18 12:38 UTC, nicosammito commented on src/components/pill/Pill.style.scss
> +}
Please look at the wrapper functionality of scss and also BEM

2024-02-18 12:38 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +    variant?: "primary" | "secondary" | "info" | "success" | "warning" | "error",
change this to color

2024-02-18 12:38 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +}
I don’t think we need a content component here.

2024-02-18 12:52 UTC, Knerio commented on src/components/pill/Pill.style.scss
> +);
We should just add a few more

2024-02-18 12:55 UTC, Knerio commented on __snapshots__/pill--with-href-chromium.png
![image](https://github.com/code0-tech/pictor/assets/96529060/5f3d26f0-c9d1-4c18-9938-813b69654f8a)
![Uploading image.png…]()

2024-02-18 13:14 UTC, Knerio commented on src/components/pill/Pill.style.scss
> +);
What should we do now?

2024-02-18 14:51 UTC, Knerio commented on src/components/pill/Pill.style.scss
> +);
Maybe we should do something like the variants, so that we have instead of an $variants array and array for like font sizes for specific Sizes, maybe we could fix that in https://github.com/code0-tech/pictor/pull/66 because there are also sizes in the utils

2024-02-18 15:17 UTC, Knerio commented on src/components/pill/Pill.style.scss
> +);
I would say that would be resolved here https://github.com/code0-tech/pictor/pull/66/commits/42fcd6bf6f7c4a199637baca83c58a19ae30b7d6#diff-39d5aa9e27fa49139a93a25f23ca7e34422ec0751ee97b761ee6322f69a7ec85

2024-02-18 15:30 UTC, nicosammito requested changes

2024-02-18 15:30 UTC, nicosammito commented on __snapshots__/pill--with-href-chromium.png
Than you should find out where this comes from

2024-02-18 16:29 UTC, nicosammito requested changes

2024-02-18 16:29 UTC, nicosammito commented on src/components/button/Button.style.scss
> +  .button--#{$name} {
add margin-left from &__icon + &__content also to dynamic size

2024-02-18 16:29 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +            <span id={`pill__label`} className={`pill__label ${removeButton ? "pill__label--active" : ""}`}>{children}</span>
why does it have an id?

2024-02-18 16:29 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +            <span id={`pill__label`} className={`pill__label ${removeButton ? "pill__label--active" : ""}`}>{children}</span>
why to develop an extra label. can be directly parsed into the pill itself

2024-02-18 16:29 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +        className={`pill pill--${color} pill--${size}`}
you need to set all the other props that you can parse in from HTMLAttr

2024-02-18 17:02 UTC, Knerio commented on src/components/button/Button.style.scss
> +  .button--#{$name} {
The margin isnt needed anyways

2024-02-18 18:00 UTC, Knerio commented on src/components/pill/Pill.tsx
> +            <span id={`pill__label`} className={`pill__label ${removeButton ? "pill__label--active" : ""}`}>{children}</span>
But I remove that, i cant style the "label"

2024-02-18 18:27 UTC, nicosammito commented
The component is not finished developing, why are you requesting my review

2024-02-18 18:36 UTC, nicosammito requested changes

2024-02-18 18:36 UTC, nicosammito commented on src/components/button/Button.style.scss
>    }
you need to add the margin-left with dynamic size at the bottom. You cant just remove this style

2024-02-18 18:36 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +    argTypes: {
missing a lot of args like placement

2024-02-18 18:36 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +const MultiSelect: React.FC<SelectType> = (props) => {
please remove a lot of unnecessary wrappers and classnames.

2024-02-18 18:36 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
If not defaultValue is provided we need to show the placeholder

2024-02-18 18:36 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                                    return <Pill size={"sm"} color={"secondary"} key={index} removeButton={true}
Currently there is no spacing between different pills

2024-02-18 18:40 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
But the defaultValue acts like a placeholder, and if the user doesnt provide a placeholder its just an empty component

2024-02-18 18:44 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
no the placeholder is the placeholder and nothing else. If a defaultValue is provided we should not show the placeholder

2024-02-18 18:44 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
This is normal behavior for inputs

2024-02-18 18:46 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
The placeholder is the string in the value and the defaultValue is the selected keys

2024-02-18 18:48 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
yep correct 👍🏻 . And we do not want to show the placeholder if a defaultValue is provided

2024-02-18 18:50 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
But why? Why cant you see both?

2024-02-18 18:52 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
a placeholder should function like a placeholder. As the name indicates it's just a temporary text that's shown when nothing is selected. Look at some normal inputs and you will see how the placeholder behaves.

2024-02-18 18:53 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
![image](https://github.com/code0-tech/pictor/assets/96529060/a112c14f-34de-4c04-8724-64884e27b096)
for example there is also a placeholder shown if  values are selected

2024-02-18 18:54 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
And this behavior is wrong.

2024-02-18 18:54 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
Okay then i will implement this

2024-02-18 18:56 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                            {[...selection].length < 1 ? <input defaultValue={placeholder ?? ""} className={"multi-select__input"}
![Bildschirmfoto 2024-02-18 um 19 54 49](https://github.com/code0-tech/pictor/assets/60352747/23eec2b3-6652-440c-8955-0aab9b1e399b)
![Bildschirmfoto 2024-02-18 um 19 54 41](https://github.com/code0-tech/pictor/assets/60352747/550a94af-888f-4d80-9cbb-a5edf680d25a)

Here you see how a normal input behaves with placeholder. As no value is provided the placeholder is shown. If a value is provided the placeholder gets replace. Placeholder means "Platzhalter" in German, so it should function as the name indicates.

2024-02-18 18:58 UTC, nicosammito requested changes

2024-02-18 18:58 UTC, nicosammito commented on src/components/pill/Pill.tsx
> +        size = "md",
the standard should be sm

2024-02-18 20:30 UTC, nicosammito requested changes

2024-02-18 20:30 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                                   readOnly></input>: null}
the placeholder is not reset if you deselect every option after you set one

2024-02-18 20:30 UTC, nicosammito commented on src/components/pill/Pill.style.scss
> +      @include box(false, $color);
remove the border from pills

2024-02-18 20:30 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +        placement: {
set "bottom start" as default

2024-02-18 21:11 UTC, Taucher2003 requested changes

2024-02-18 21:11 UTC, Taucher2003 commented on src/components/button/Button.style.scss
> +    padding: $font-size / 2;
```suggestion
    padding: calc($font-size / 2);
```

2024-02-18 21:11 UTC, Taucher2003 commented on src/components/pill/Pill.style.scss
> +        margin-right: $font-size / 2;
```suggestion
        margin-right: calc($font-size / 2);
```

2024-02-18 21:11 UTC, Taucher2003 commented on src/components/pill/Pill.style.scss
> +      padding: $font-size / 2;
```suggestion
      padding: calc($font-size / 2);
```

2024-02-20 14:47 UTC, nicosammito requested changes

2024-02-20 14:47 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +const meta: Meta = {
Missing a lot of props here. For example disabled. Try to implement as many as you can

2024-02-20 14:47 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +}
Can’t this be removed?

2024-02-20 14:47 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                                   readOnly></input>: null}
This is still a problem

2024-02-20 14:47 UTC, nicosammito commented on src/components/button/Button.style.scss
> +@each $name, $font-size in $sizes {
The size is not being set correctly. Check button on storybook and change sizes. You will see the problem

2024-02-20 14:47 UTC, nicosammito commented on src/components/button/Button.style.scss
> +
Why to include a box here. The Color is set over the button—color class

2024-02-20 14:47 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +            <Menu placement={placement} defaultSelectedKeys={defaultValue ?? ""} selectionMode={"multiple"}
When clicking on the pill remove button the Menu state changes. Thus need to be prevented

2024-02-20 15:17 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +                                   readOnly></input>: null}
This was fixed some while ago

2024-02-20 15:33 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                                   readOnly></input>: null}
But it is still a problem. In my browser it does not work

2024-02-20 15:34 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +const meta: Meta = {
Why you are resolving it? It’s not resolved until you commit something that fixes this 😄

2024-02-20 15:35 UTC, nicosammito commented on src/components/button/Button.style.scss
> +@each $name, $font-size in $sizes {
Until its not fixed, we are not resolving this

2024-02-20 15:54 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +const meta: Meta = {
https://github.com/code0-tech/pictor/pull/64/commits/4cfdadca8517a5110919fad44d41c82255d521f1

2024-02-20 15:54 UTC, Knerio commented on src/components/button/Button.style.scss
> +@each $name, $font-size in $sizes {
https://github.com/code0-tech/pictor/pull/64/commits/5a2a5eba7488989f284e869a788849f696279be3

2024-02-20 16:04 UTC, Knerio commented on src/components/button/Button.style.scss
> +
[85644d6](https://github.com/code0-tech/pictor/pull/64/commits/85644d6f3a2cdeb9a04410bb0cecbee5fb134b83)

2024-02-20 16:11 UTC, nicosammito requested changes

2024-02-20 16:11 UTC, nicosammito commented on __snapshots__/multiselect--basic-multi-select-chromium.png
Why does this image has been changed? lets not set a defaultValue for Storybook

2024-02-20 20:41 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +            <Menu placement={placement} defaultSelectedKeys={defaultValue ?? ""} selectionMode={"multiple"}
[ff2e6ec](https://github.com/code0-tech/pictor/pull/64/commits/ff2e6ec4c0d92a913ee5f87edb21e4dbc05429b5) or some other of you

2024-02-24 13:53 UTC, nicosammito requested changes

2024-02-24 13:53 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +        </div>
On mobile devices you can’t open the Multiselect. I assume this comes from the input inside the Multiselect component. Please try to get the same error, otherwise you got a video describing the error

2024-02-24 13:53 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +        children, label, maxValues = -1,
MaxValues can’t be less than 1, because you habe to select at least one value otherwise the component does not make any sense

2024-02-24 13:53 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +        children, label, maxValues = -1,
If you do not have a maxValue it should be undefined

2024-02-24 13:57 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +        </div>
I´d would be good if you would provide a video

2024-02-24 13:59 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +        </div>
You will find this in our Closed Team chat

2024-02-24 14:08 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.tsx
> +        children, label, maxValues = -1,
[fc2caee](https://github.com/code0-tech/pictor/pull/64/commits/fc2caee34443176ad392330a3138c0afd8a05256)

2024-02-24 14:14 UTC, nicosammito requested changes

2024-02-24 14:14 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                      if (maxValues !== undefined && (keys.size > maxValues && selectedArray.length < keys.size)) return
```suggestion
                      if (maxValues && (keys.size > maxValues && selectedArray.length < keys.size)) return
```

2024-02-24 14:14 UTC, nicosammito commented on src/components/MultiSelect/MultiSelect.tsx
> +                                                 if (maxValues !== -1 && maxValues!! > 0 && (newSelection.size > maxValues!! && selectedArray.length < newSelection.size)) return
```suggestion
                                                 if (maxValues && maxValues > 1 && (newSelection.size > maxValues && selectedArray.length < newSelection.size)) return
```

2024-02-24 16:19 UTC, Knerio commented on src/components/MultiSelect/MultiSelect.stories.tsx
> +        </div>
I dont know why this is happening, i allready changed the input to a span, but i dont know whats the next step

2024-02-27 19:16 UTC, nicosammito requested changes

2024-02-29 13:08 UTC, nicosammito commented
https://layers.to/layers/clmnlbd570001n00cwpyyxwji

Let’s bring the Multiselect as close to this as possible

2024-05-18 13:04 UTC, closed without merging