New Type for Variants
code0-tech/pictor pull request #66
Opened 2024-02-17 21:38 UTC by Knerio

This would resolve https://github.com/code0-tech/pictor/issues/50

2024-02-18 12:32 UTC, nicosammito submitted a review, later dismissed
Overall nicely done, but as you see in #59 we are changing from Variant to Color, because Variant is used differently now

2024-02-18 12:34 UTC, Knerio commented
> Overall nicely done, but as you see in #59 we are changing from Variant to Color, because Variant is used differently now

Thats true, but in https://github.com/code0-tech/pictor/pull/64 that would be a problem

2024-02-18 12:36 UTC, Knerio commented
> > Overall nicely done, but as you see in #59 we are changing from Variant to Color, because Variant is used differently now
> 
> Thats true, but in #64 that would be a problem

Or we could implement these styles but we also need to fix the @include box then for all the new variants

2024-02-18 12:43 UTC, nicosammito commented
> > Overall nicely done, but as you see in #59 we are changing from Variant to Color, because Variant is used differently now
> 
> Thats true, but in #64 that would be a problem

Yeh we need to change this in all components from now on. Just change variant: “bla” | “bla” to color: “bla” | “bla”

2024-02-18 15:28 UTC, nicosammito requested changes

2024-02-18 15:28 UTC, nicosammito commented on src/components/alert/Alert.tsx
> +    variant: Color
should be renamed also to color

2024-02-18 15:28 UTC, nicosammito commented on src/styles/_variables.scss
> +);
parse in directly the font sizes rather to map in map

2024-02-18 15:28 UTC, nicosammito commented on src/components/button/Button.stories.tsx
> +                    return <Button disabled={disabled} color={value}>
why you are removing the variant. Button have a variant and a color

2024-02-18 15:28 UTC, nicosammito commented on src/components/FontSizes/Font.style.scss
> +  .size__#{$name} {
look at BEM. should be size--

2024-02-18 15:28 UTC, nicosammito commented on src/components/FontSizes/Font.tsx
> +const Font: React.FC<FontType> = (props) => {
rename font to Text

2024-02-18 15:28 UTC, nicosammito commented on src/components/FontSizes/Font.tsx
> +    return <text className={`size__${size}`}>
should be a span

2024-02-18 15:28 UTC, nicosammito commented on src/components/FontSizes/Font.tsx
> +export interface FontType {
allow also all html span props

2024-02-18 15:28 UTC, nicosammito commented on src/utils/utils.ts
> +
outsource this to a Color file inside the util folder

2024-02-20 14:36 UTC, nicosammito requested changes
Just some minor changes before we can merge

2024-02-20 15:30 UTC, nicosammito requested changes

2024-02-20 15:30 UTC, nicosammito commented on src/components/FontSizes/Text.stories.tsx
> +            <Button>
Could you also remove the button. Let’s just show the text

2024-02-20 15:30 UTC, nicosammito commented on src/components/FontSizes/Text.tsx
> +export interface FontType extends Omit<Omit<Omit<HTMLProps<HTMLSpanElement>, "children">, "className">, "size"> {
Do we need to omit the className?

2024-02-20 20:40 UTC, Knerio commented on src/components/FontSizes/Text.stories.tsx
> +            <Button>
[65e7129](https://github.com/code0-tech/pictor/pull/66/commits/65e7129408c22c5d3580c440ef2e00b7df5101dc)

2024-02-20 20:40 UTC, Knerio commented on src/components/FontSizes/Text.tsx
> +export interface FontType extends Omit<Omit<Omit<HTMLProps<HTMLSpanElement>, "children">, "className">, "size"> {
[2c063cd](https://github.com/code0-tech/pictor/pull/66/commits/2c063cdac914350be58057316b5a2e55208569ec)

2024-02-24 13:45 UTC, nicosammito approved these changes
Nicely done

2024-02-24 13:58 UTC, nicosammito approved these changes

2024-02-24 14:00 UTC, merged